# Cluster
cluster.name: ${SERVICE_NAME}


# Network
transport.bind_host: ${MULIT_IP}
transport.publish_host: ${HOST_IP}

http.port: 9200

# Node
node:
  name: ${POD_ORDER}
  master: ${NODE_MASTER}
  data: ${NODE_DATA}

# bootstrap
# bootstrap.mlockall: true

# http
http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: true

# Paths
path:
  logs: /data/logs/${POD_ORDER}
  data: /data/data/${POD_ORDER}
  plugins: /data/plugins/${POD_ORDER}
  
# Discovery
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.multicast.enabled: ${MULTICAST}
#discovery.zen.ping.unicast.hosts: []
