# ---------------------------------- Cluster -----------------------------------
cluster.name: es


# ---------------------------------- Network -----------------------------------
network.host: 0.0.0.0

http.port: 9200

# ------------------------------------ Node ------------------------------------
node.name: ${POD_ORDER}

# ----------------------------------- Paths ------------------------------------
path:
  logs: /data/logs/${POD_ORDER}
  data: /data/data/${POD_ORDER}
  
# --------------------------------- Discovery ----------------------------------
discovery.zen.minimum_master_nodes: 1

  
