# ---------------------------------- Cluster -----------------------------------
cluster.name: es


# ---------------------------------- Network -----------------------------------
network.host: ${HOST_IP}

http.port: 9200

# ------------------------------------ Node ------------------------------------
node.name: ${POD_ORDER}

# ----------------------------------- Paths ------------------------------------
path:
  logs: /data/logs/${POD_ORDER}
  data: /data/data/${POD_ORDER}
  
# --------------------------------- Discovery ----------------------------------
discovery.zen.minimum_master_nodes: 1

discovery.zen.ping.multicast.enabled:true

  
